### ISSUE TITLE
Slider does not work with pyside6

### ISSUE THREAD

**Issue by robochopbg** [niklashenning/pyqt-advanced-slider#6]
As soon as you call this Slider class

window.py", line 266, in paintEvent
text_width = metrics.width(value_string_full)
AttributeError: 'PySide6.QtGui.QFontMetrics' object has no attribute 'width'

**Comment by robochopbg** [comment]
You need to change
text_width = metrics.width(value_string_full)
to 
text_width = metrics.horizontalAdvance(value_string_full)

**Comment by robochopbg** [comment]
There are bigger issues with this code especially you paint method.

The paint methods gets called constantly so it pushes the cpu usage up to like 30%.
Making this really bad code.

**Comment by niklashenning** [comment]
Interesting, it works with the PySide6 version that I'm using. I will take a look at it later.

Regarding your other comment, I addressed this in #7
