### ISSUE TITLE
Problem with Paint method

### ISSUE THREAD

**Issue by robochopbg** [niklashenning/pyqt-advanced-slider#7]
The paint methods gets called constantly so it pushes the cpu usage up to like 30%.
Making this really bad code.

**Comment by niklashenning** [comment]
Yes, this constant repainting is unnecessary. Thanks for bringing this to my attention. I've implemented a fix so it only repaints when it's actually necessary, and the CPU usage has gone down to around 0% for me. 

I will push it this weekend.

**Comment by robochopbg** [comment]
Great thanks.

i'll check it out.
Good work. I do like your slider as the qt standard one is horrible.
Thank you
